### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by alishkaahmadov** [SerNet/verinice-veo#2]
I am running project via bootRun. Changed all necessary properties in application.yaml file (security:oauth2:resourceserver:jwt). But it's still returns 401. Should I change/add something in keycloak console or in another java files?

**Comment by Agh42** [comment]
Sounds like your missing a proper Keycloak scope configuration - please shoot me a PM an I will send you one personally. We can also continue this discussion via PM.

Just a heads up: I`ll be closing the "Issue" section here on GitHub as we`re trying to channel all support requests and discussions on our own site at [verinice.com](https://verinice.com) in the forum. We are just publishing our source code here and on other platforms as well - we`re not using GitHub to track issues for this project.
